package com.example.mynotebook.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF774F83)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFAD7FF)
val onPrimaryContainerLight = Color(0xFF2E0A3B)
val secondaryLight = Color(0xFF6A596C)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF2DCF3)
val onSecondaryContainerLight = Color(0xFF241727)
val tertiaryLight = Color(0xFF904A46)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDAD7)
val onTertiaryContainerLight = Color(0xFF3B0809)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF7FB)
val onBackgroundLight = Color(0xFF1F1A1F)
val surfaceLight = Color(0xFFFFF7FB)
val onSurfaceLight = Color(0xFF1F1A1F)
val surfaceVariantLight = Color(0xFFEBDFE9)
val onSurfaceVariantLight = Color(0xFF4C444C)
val outlineLight = Color(0xFF7E747D)
val outlineVariantLight = Color(0xFFCFC3CD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF342F34)
val inverseOnSurfaceLight = Color(0xFFF8EEF5)
val inversePrimaryLight = Color(0xFFE6B6F1)

val primaryDark = Color(0xFFE6B6F1)
val onPrimaryDark = Color(0xFF452152)
val primaryContainerDark = Color(0xFF5E386A)
val onPrimaryContainerDark = Color(0xFFFAD7FF)
val secondaryDark = Color(0xFFD5C0D7)
val onSecondaryDark = Color(0xFF3A2B3D)
val secondaryContainerDark = Color(0xFF514254)
val onSecondaryContainerDark = Color(0xFFF2DCF3)
val tertiaryDark = Color(0xFFFFB3AE)
val onTertiaryDark = Color(0xFF571E1C)
val tertiaryContainerDark = Color(0xFF733330)
val onTertiaryContainerDark = Color(0xFFFFDAD7)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF161217)
val onBackgroundDark = Color(0xFFEAE0E7)
val surfaceDark = Color(0xFF161217)
val onSurfaceDark = Color(0xFFEAE0E7)
val surfaceVariantDark = Color(0xFF4C444C)
val onSurfaceVariantDark = Color(0xFFCFC3CD)
val outlineDark = Color(0xFF988E97)
val outlineVariantDark = Color(0xFF4C444C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEAE0E7)
val inverseOnSurfaceDark = Color(0xFF342F34)
val inversePrimaryDark = Color(0xFF774F83)




